### ISSUE TITLE
App‑design‑v2.5

### ISSUE THREAD

**Issue by macsleven** [planetdecred/dcrios#100]
Designs to be completed
- [x] 0. - Loading Screen

- [x] 1. - Start

- [x] 2.0 - New wallet

- [ ] 2.2 - New Wallet

- [ ] 2.3 - Starting new wallet

- [ ] 3.0 - Recover wallet

- [x] 4.0 - Overview home

    - [x] 4.0.1 - Menu (#139)  

- [x] 4.1 - Accounts (#140)

- [x] 4.1.1 - Account details (#140)

- [x] 4.2 - Send empty

    - [ ] 4.2.1 - Send filled

    - [x] 4.2.1 - Send filled DCR only

- [ ] 4.2.2 - Send Filled SEND pressed

    - [ ] 4.2.2 - Send Filled SEND pressed – 1 

- [x] 4.2.3 - Send completed

- [x] 4.3 - Receive Filled

- [x] 4.4 - History

   - [ ] 4.4 - History & Filters

- [ ] 4.4.2 - Transaction Details

- [ ] 4.5 - Settings

- [x] 4.6 Help (#141)

- [x] fetching headers (#147)

- [x] rescanning chain (#147)

- [x] chain connected (#147)

- [ ] Password Tab

- [ ] Pin Tab

**Comment by macsleven** [comment]
Reference:
https://xd.adobe.com/spec/08bd90ab-fc58-4f47-5423-569db1e94887-7e8c/

**Comment by ensoreus** [comment]
https://xd.adobe.com/view/9326fbf7-3936-4c7a-6430-c0dca703da98-e517/?hints=off

new link

**Comment by dreacot** [comment]
fixed in master
