### ISSUE TITLE
Disable screenshot on seed pages

### ISSUE THREAD

**Issue by C-ollins** [planetdecred/dcrios#270]

**Comment by macsleven** [comment]
Users cannot be prevented from taking screenshot on IOS.

**Comment by degeri** [comment]
Some links: 

https://tumblr.jeremyjohnstone.com/post/38503925370/how-to-detect-screenshots-on-ios-like-snapchat

https://medium.com/@abhimuralidharan/detecting-screen-capturing-in-ios-11-cca15881c785
