### ISSUE TITLE
iPod Touch layout fixes

### ISSUE THREAD

**Issue by macsleven** [planetdecred/dcrios#294]
Tap area is to the left of the actual 3 dots, some text is cut off, bottom area is cut off.
<img src="https://user-images.githubusercontent.com/794430/54997598-62249c80-4fcc-11e9-8b9b-866cbd9c0a42.jpg" width="300">

Row height and text position looks off on the nav bar. Also, balance line text being cut off.
<img src="https://user-images.githubusercontent.com/794430/54997765-bd568f00-4fcc-11e9-9c19-8461df9f46af.jpg" width="300">

On overview screen recent activity is scrolling limit the number of items displayed to avoid scrolling.
Some text on the Sending Decred page is unreadable.
And text on other screens are been chopped off too, please refer to iPod touch or 5s

**Comment by macsleven** [comment]
Nav side menu should show some kind of down and up arrows on the top and bottom to indicate when it is scrollable for small screens.

**Comment by dreacot** [comment]
fixed in master
