### ISSUE TITLE
ui: seed verification page issues

### ISSUE THREAD

**Issue by itswisdomagain** [planetdecred/dcrios#326]
The following were observed on the seed verification page while testing on a 5th generation iPad simulator:
- Clicking an empty space (outside any of the word buttons) causes issues with the auto scroll

- Confirm button doesn't look disabled
(android)
![Screenshot 2019-04-08 at 1 43 05 AM](https://user-images.githubusercontent.com/18400051/55698120-5669aa80-59bc-11e9-9cfc-d4971120dbc2.png)
(ios)
![Screenshot 2019-04-08 at 1 43 09 AM](https://user-images.githubusercontent.com/18400051/55698125-5b2e5e80-59bc-11e9-9cf0-91add5a5d1de.png)

- On android, selecting one or more wrong words on the seed verification page shows an error just above the button. On ios, I have to click the button on ios to get similar error
(android)
![Screenshot 2019-04-08 at 1 49 42 AM](https://user-images.githubusercontent.com/18400051/55698139-6a151100-59bc-11e9-9661-5a53efb23dbf.png)
(ios, after clicking the button)
![Screenshot 2019-04-08 at 1 49 53 AM](https://user-images.githubusercontent.com/18400051/55698169-8fa21a80-59bc-11e9-88bd-7ea808d815e4.png)

**Comment by dreacot** [comment]
fixed in master
