### ISSUE TITLE
ipod touch visual issues, Send page, and overview

### ISSUE THREAD

**Issue by raedah** [planetdecred/dcrios#353]
- Tap to paste button is not the right size.
- Address is not fitting into viewable area when cursor is in editing mode.
- More horizontal space is needed between  DCR and SEND MAX, ipod touch.
- Large numbers are getting cut off on the send line 9104.291222536, part of the 9 is chopped off.
- The send button is too close to the bottom of the page on ipod and should move up into the available white space.
- Transaction successful dialog is not displaying correctly on ipod.
- Overview page, buttons on the bottom have excess white space at the bottom of the screen. non proportional. ipod.
- button icons are floating off to the left for the send and receive buttons on the overview page.
- password input box on the send dialog is hidden underneath the keyboard.

**Comment by dreacot** [comment]
fixed in master
