### ISSUE TITLE
debug symbol compile failure

### ISSUE THREAD

**Issue by raedah** [planetdecred/dcrios#361]
Seems to be causing the app validator to fail which prevents us from getting proper crash logs from the app store. The Strip Swift symbols feature is failing.

**Comment by itswisdomagain** [comment]
Since #367 and #368, most build warnings are cleared. Currently unable to confirm, but it seems a couple warnings show up when building for Generic iOS Device from Xcode.

**Comment by raedah** [comment]
Still have debug symbols error remaining to resolve. Only occurs when building for Generic Device. Need this for full debug reports from the apple store.

**Comment by raedah** [comment]
This issue is not actually resolved. The error still occurs when archiving.

Upstream cause is here https://github.com/golang/go/issues/28997

**Comment by dreacot** [comment]
fixed in master
