### ISSUE TITLE
ipad mini layout issues

### ISSUE THREAD

**Issue by raedah** [planetdecred/dcrios#383]
Wallet create page, elements are not centered on the page, fonts can be scaled larger.

Seed Restore page, font size can be scaled larger. 

Pin page, should be centered and scaled larger, similar to the ipod unlock screen.

Welcome dialog, font should be scaled larger, text needs to be left justified.

Wifi dialog, scale larger.

Overview synchronizing, scale all text larger. Make progress bar thicker.

Nav bar, scale up to use unused space. Narrow the nav bar width to reduce wasted space. 

Overview and Transaction list. iPads have a lot more screen space for the vertical number of transactions to show, as well as unused center space on the horizontal rows. We can display the date as its own column rather then having it with the confirmed status. We can make the rows slightly taller and increase the font size throughout.

Nav bar button on top left, should be larger.

Send page, increase font sizes for readability. Address font should be large enough to take up the available space on the screen. From drop down is extending to 100% width when it should only extend to the width needed for the account text. Qrcode button can likely be bigger. Tap to paste button is not correctly sized relative to the font size within it.

Receive page, Account drop down is extending to 100% width when it should only extend to the width needed for the account text. Address copied dialog box font is too small.

Security page, input rows appear to be floating above the underlines. Increase font sizes. Address area should show the full address with no empty space.

Accounts page, increase font size and row height.

Help page, increase font size.

Settings page, Save button on the top is not obvious. Need to be better designed, or removed like on android.

tx details page, full hash is not showing, instead it shows ... in the middle. This is not needed because there is plenty of room on this page to show the full hash.

**Comment by dreacot** [comment]
no longer relevant, issue was created for an old UI design

New Ipad layout would be revisited here #822
