### ISSUE TITLE
Send page -> Send max -> Visual indicator when enabled

### ISSUE THREAD

**Issue by itswisdomagain** [planetdecred/dcrios#434]
If a user presses the "SEND MAX" button, all funds in the selected account will be sent to the destination address/account when he hits "SEND"

The only exception is if he manually edits the amount after previously hitting "SEND MAX", then the new amount entered will be used for the send operation.

Having a visual indicator when "SEND MAX" is enabled will help a user easily recognise/remember that he has indicated to send all funds in the currently selected account. This becomes especially useful if the user gets distracted from the send process (probably leaving the send page or his phone) and then returns to the send page.

The "SEND MAX" button can behave like a toggle. Highlighted when active and vice versa. Clicking the "SEND MAX" when already active can be made to disable the send max feature. Or we could maintain the current behaviour of only disabling the feature when the user edits the amount.

**Comment by dreacot** [comment]
fixed in https://github.com/planetdecred/dcrios/pull/807
