### ISSUE TITLE
Sending Decred > QR Code detection not working until restart of app

### ISSUE THREAD

**Issue by chillviben** [planetdecred/dcrios#601]
_DCR Wallet Mainnet
iPad Mini 13.2.2
v1.0.1 / build 2020-02-26_

Trying to input destination address via QR code.
I tap QR icon and grant camera permissions.
Camera viewer comes up and I aim at QR code but it's not detected.
Tried numerous times with different QR codes and bright backlighting.  
After closing and restarting the wallet app, I was able to successfully scan QR code.

**Comment by monsa00** [comment]
This was on a very old version at this point, need to verify on latest version.
