### ISSUE TITLE
Tapable area to switch currency input boxes on send page

### ISSUE THREAD

**Issue by raedah** [planetdecred/dcrios#646]
The first toggleable area is the tiny icon in the middle of the values. That should be tapable. In addition, the lower value which is not editable should be tapable to trigger the switching of upper and lower values.

**Comment by JustinBeBoy** [comment]
@raedah 
You want is that when you click on the currency switch in image 1 it will look like image 2 and be able to edit the value

image 1
<img width="410" alt="dcr1" src="https://user-images.githubusercontent.com/19331824/89751352-df857a00-daf9-11ea-9698-467a5892a9f7.png">

image 2
<img width="407" alt="drc2" src="https://user-images.githubusercontent.com/19331824/89751472-676b8400-dafa-11ea-8044-10fcf2b2393a.png">

**Comment by macsleven** [comment]
Yes, the top value should always be editable.

**Comment by macsleven** [comment]
Fixed in #713
