### ISSUE TITLE
Verify the current pin before next step

### ISSUE THREAD

**Issue by Michae2xl** [planetdecred/dcrios#705]
Change/startup PIN/password -> verify the current pin before next step  

![A6CA4894-564D-4C64-B334-D5777B59BE3F](https://user-images.githubusercontent.com/44928059/85655817-07219f80-b67e-11ea-9170-32776f3f6f09.jpeg)

**Comment by gravityz3r0** [comment]
Verifying current password immediately encourages password guessing spam, therefore some sort of blocking and cooldown must be implemented after a pre determined amount of failed attempt.

**Comment by Michae2xl** [comment]
Hmm, well, what is better for user and security and I’m in.
