### ISSUE TITLE
overview: new transaction replaces the first transaction in the list

### ISSUE THREAD

**Issue by C-ollins** [planetdecred/dcrios#744]
After making send transaction, the transaction is displayed on the overview page but it replaces the first transaction in the list, instead of prepending it to the list. I have two transactions in my wallet after sending `10 DCR`  out and this is what it looks like:
<img width="300" src="https://user-images.githubusercontent.com/19960200/113582236-057b0400-9620-11eb-958c-6778af8ef4fa.jpg" >

It shows properly when the page is refreshed:
<img width="300" src="https://user-images.githubusercontent.com/19960200/113582280-1461b680-9620-11eb-8132-9e027daa446f.jpg" >

**Comment by raedah** [comment]
Sounds like this should be fixed as well.
