### ISSUE TITLE
Mixed transactions should be labeled as 'Mix'

### ISSUE THREAD

**Issue by macsleven** [planetdecred/dcrios#756]
Mixed transactions should be labeled as 'Mix', modifications should be made in the transaction row and transaction details dialog title. Also, remove the double negative sign from the amount and the amount should be the mix denomination(`mix_denom` in the transaction json).
<img src="https://user-images.githubusercontent.com/19960200/118499205-9e706500-b71e-11eb-9d7f-12bc5bd3244f.jpg" width="300">

**Comment by dreacot** [comment]
@macsleven on dcrandroid, the mix transaction details title shows 'Sent' and not 'Mix'

i'm mentioning it cause this issue says we should change it to 'Mix'
