### ISSUE TITLE
Show an exponential value when the mixer completes

### ISSUE THREAD

**Issue by macsleven** [planetdecred/dcrios#761]
The unmixed balance shows an exponential value when the mixer completes
![Screenshot from 2021-05-12 16-29-10](https://user-images.githubusercontent.com/25265396/118282754-8900fe00-b4c6-11eb-97e8-19b8a98092cb.png)

**Comment by dreacot** [comment]
I ran the mixer again and couldn't replicate so this can be closed @macsleven 


<img src="https://user-images.githubusercontent.com/25265396/118535774-ca9ddd00-b742-11eb-9627-6db5670d664f.png" width="300" />
