### ISSUE TITLE
Mix transactions shows as 'Sent' on tx dialog

### ISSUE THREAD

**Issue by C-ollins** [planetdecred/dcrios#783]
This is the tx dialog shown for a mix transaction.  

<img src="https://user-images.githubusercontent.com/19960200/120058613-0e96b900-c044-11eb-8514-ca27909b0677.PNG" height="500">

**Comment by dreacot** [comment]
@C-ollins I believe @macsleven fixed this in the mixer PR, cause I saw the change when I reviewed the PR
