### ISSUE TITLE
trying to view logs freezes the UI

### ISSUE THREAD

**Issue by dreacot** [planetdecred/dcrios#791]
After I clicked on the view log row, the UI started showing a loader, while waiting for the loading to finish, I could not go back to the previous page. 

The loader locks the UI to that page, and the only way to exit was to close the app and reopen it

<img src="https://user-images.githubusercontent.com/25265396/120119178-29754480-c18e-11eb-8a85-843fd2b8f4cf.png" width="300" >

**Comment by macsleven** [comment]
Can this error be reproduced?

**Comment by dreacot** [comment]
> Can this error be reproduced?

haven't been able to replicate again

**Comment by dreacot** [comment]
@macsleven but even for the few seconds which it takes the Log the show while loading, you can't navigate back or to another tab,  we need to prevent the loader for locking the entire UI

what do you think?
