### ISSUE TITLE
app crashes while trying to load proposal details from the server

### ISSUE THREAD

**Issue by dreacot** [planetdecred/dcrios#838]
The app crashes on first run while trying to load proposal details.

I first launched the app, created a wallet, then waited a few seconds, before going to the more page, clicking the politeia page and then clicking the first proposal in the list, the proposal details pages was opened, and then the loading UI was displayed for about 10 seconds before the app crashed.

Returning back to the app, the proposal details for said proposal was already loaded, and the issue didn't occur for other proposals

**Comment by macsleven** [comment]
I have tested this using your description and i haven't been able to reproduce the crash, can you easily Reproduce this, if yes, you can provide the log of the crash

**Comment by dreacot** [comment]
i can no longer reproduce the crash
