### ISSUE TITLE
DCR balances on the privacy page should be displayed in 8 decimal places.

### ISSUE THREAD

**Issue by dreacot** [planetdecred/dcrios#852]
DCR balances on the privacy page should be displayed in 8 decimal places.

<img src="https://user-images.githubusercontent.com/25265396/134095877-68b97651-1963-45be-88ad-2537bd2e1d72.jpeg" width="300"/>

**Comment by JustinBeBoy** [comment]
I have tested and it displayed in 8 decimal
<img src="https://user-images.githubusercontent.com/19331824/134296243-73fb214e-e986-4a48-a7d2-8458af56a69a.jpg" width="300">
l

**Comment by dreacot** [comment]
From your screenshot, your unmixed balance is in 6 decimal places

This is the expected behaviour

![Screenshot_20210921-135514_Decred Wallet Testnet](https://user-images.githubusercontent.com/25265396/134301718-cdf5ce1a-2221-4eb3-af21-6cf74f151285.jpg)
