### ISSUE TITLE
Replace all instances of "seed phrase" with "seed words" 

### ISSUE THREAD

**Issue by Clariceco** [planetdecred/dcrios#863]
Find/Replace ALL: "seed phrase" with 'seed words', 
@macsleven @JustinBeBoy

**Comment by JustinBeBoy** [comment]
I agree with @monsa00 . But I think we will keep intact "seed phrase". 
<img width="302" alt="image" src="https://user-images.githubusercontent.com/19331824/141602318-59f0e6d3-8c84-45bb-8fbe-4612796154a6.png">

**Comment by monsa00** [comment]
Yes this is fine, makes sense to me as well.

Thanks

**Comment by monsa00** [comment]
> I agree with @monsa00 . But I think we will keep intact "seed phrase". <img alt="image" width="302" src="https://user-images.githubusercontent.com/19331824/141602318-59f0e6d3-8c84-45bb-8fbe-4612796154a6.png">

After second review, let's change this dialog to say "The 33 seed words are EXTREMELY IMPORTANT" to match the rest of the app language. Thanks.
